version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies" 
  - package-ecosystem: "go" #peut etre gomod
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies" 
