name: Lint Workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run semgrep
        uses: returntocorp/semgrep-action@v1

  dockerfile-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Run Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile

  super-linter:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4
