name: Lint Workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

      - name: Run Hadolint
        uses: hadolint/hadolint@v1.17.5-debian
        with:
          files: Dockerfile

      - name: Run Super-Linter
        uses: github/super-linter@v4.12.0
        if: github.event_name == 'pull_request'
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} #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
