name: Lint Workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run semgrep
        uses: returntocorp/semgrep-action@v1

  docker_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: launching of hadolint
        uses: hadolint/hadolint@v2

  super-linter:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4
