name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Build and Release
      uses: goreleaser/goreleaser-action@v2
      if: success()
      with: 
        version: latest 
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v2  

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build And Publish Image 
      uses: docker/build-push-action@v4
      with: 
        context: . 
        file: Dockerfile 
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/4dvp_docker:${{ github.ref_name }}