name: Release

on:
  push:
    tags:
      - "*"

env:
  DOCKER_USERNAME: ${{ secrets.murcyado }}
  DOCKER_TOKEN: ${{ secrets.dckr_pat_4Sp-JjjwF_Z_hIe9_21P2pjS8Yg }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install goreleaser
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

      - name: Build and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goreleaser release --rm-dist

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.murcyado }}/${{ env.4dvp-docker-test }}:${{ github.ref }}
        env:
          DOCKER_USERNAME: ${{ secrets.murcyado }}
          DOCKER_PASSWORD: ${{ secrets.dckr_pat_4Sp-JjjwF_Z_hIe9_21P2pjS8Yg }}
          DOCKER_REPOSITORY: YourRepository
