name: Release

on:
  push:
    tags:
      - "*"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} #murcyado
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} #dckr_pat_Nvlq0B6p2J3fNNIctPAKeEwGgzo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install goreleaser
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

      - name: Build and release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} #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
        run: |
          goreleaser release --rm-dist

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ github.ref }} #murcyado , 4dvp-docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} #murcyado
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }} #dckr_pat_Nvlq0B6p2J3fNNIctPAKeEwGgzo
          DOCKER_REPOSITORY: 4dvp-docker
